-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 15:52:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudenten` INT NOT NULL AUTO_INCREMENT,
  `naamStudent` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `wachtwoord` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idStudenten`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Maaltijd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Maaltijd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Maaltijd` (
  `idMaaltijd` INT NOT NULL AUTO_INCREMENT,
  `idKok` INT NOT NULL,
  `naamMaaltijd` VARCHAR(255) NOT NULL,
  `maaltijdAfbeelding` VARCHAR(255) NULL,
  `maxEters` INT NOT NULL,
  `maaltijdBeginTijd` DATETIME(6) NOT NULL,
  `maaltijdEindTijd` DATETIME(6) NOT NULL,
  `kosten` DECIMAL(2) NOT NULL,
  `beschrijving` VARCHAR(255) NULL,
  PRIMARY KEY (`idMaaltijd`, `idKok`),
  INDEX `idKok_idx` (`idKok` ASC),
  CONSTRAINT `idKok`
    FOREIGN KEY (`idKok`)
    REFERENCES `mydb`.`Student` (`idStudenten`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StudentMaaltijd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StudentMaaltijd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StudentMaaltijd` (
  `idStudent` INT NOT NULL,
  `idMaaltijd` INT NOT NULL,
  `aantalMeeEters` INT NOT NULL,
  INDEX `FK_Maaltijd_idx` (`idMaaltijd` ASC),
  CONSTRAINT `FK_Maaltijd`
    FOREIGN KEY (`idMaaltijd`)
    REFERENCES `mydb`.`Maaltijd` (`idMaaltijd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Eter`
    FOREIGN KEY (`idStudent`)
    REFERENCES `mydb`.`Student` (`idStudenten`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Student`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Student` (`idStudenten`, `naamStudent`, `email`, `wachtwoord`) VALUES (1, 'Barry', 'barry@mail.nl', 'someHash');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Maaltijd`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Maaltijd` (`idMaaltijd`, `idKok`, `naamMaaltijd`, `maaltijdAfbeelding`, `maxEters`, `maaltijdBeginTijd`, `maaltijdEindTijd`, `kosten`, `beschrijving`) VALUES (1, 1, 'Spaget', NULL, 100, '2018-01-20 18:00:00', '2018-01-20 19:00:00', 10, 'MY SPAGET');

COMMIT;

